version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "sajidfarooqnajar/devbank-backend"

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:latest .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:latest
      - printf '[{"name":"backend-container","imageUri":"%s"}]' $IMAGE_REPO_NAME:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
